### ISSUE TITLE
Add colours feature

### ISSUE THREAD

**Issue by sourabhlal** [tkw1536/jMap#11]

**Comment by tkw1536** [comment]
Make an API suggestion and I'll implement it.

**Comment by sourabhlal** [comment]
We need 4 colours per building: 2 shades of grey and 2 accents. The grey shades are already done perfectly (the light for corridors and stairs, dark for unselected rooms), and will be identical for every building.

Additionally, each building will be assigned a different set of 2 accents, primary and secondary:
Nordmetall : Primary= Yellow, Secondary = Purple //this is currently the setting for all buildings
College 3: Primary = Green, Secondary = White
Mercator: Primary = Blue, Secondary = White
Krupp: Primary = Red, Secondary = Black
Research buildings will be decided later.

I think we should have the ability to specify the colour in the appropriate js data file, and this can be somehow read and used in the css. I don't know if that's easy to implement or theres an easier solution, but imho it is the most user friendly solution.

**Comment by tkw1536** [comment]
Maybe the best idea is to add a colorscheme property to each Building
that's then added as a CSS class.
